### ISSUE TITLE
Add Lua 5.1 parser

### ISSUE THREAD

**Issue by SoniEx2** [katlogic/ljx#2]
The original LJ project has LuaJIT VM + Lua 5.1 parser. Just add a Lua 5.2 parser to it and a Lua 5.2 environment which can be used with `require"5.2"`. Then add command line flags: `-5.1`, `-5.2`, etc. The Lua 5.2 environment would have a `load` function that can compile Lua 5.2 source code into LuaJIT bytecode, for example.

LuaJIT also supports 64-bit integer literals thru "xxxLL", so you can just use that.

All you really need is to add on to the stdlib.

**Comment by katlogic** [comment]
LJX just hacked original parser (among other things) to support 5.2. Can you provide example where 5.2 support fails?

**Comment by SoniEx2** [comment]
It can't do Lua 5.1.

It can't do both Lua 5.1 and Lua 5.2 in the same VM state with limited (but good enough) interoperability.

You see, the original LuaJIT already supports _ENV.

http://www.freelists.org/post/luajit/Make-the-VM-Luaversionagnostic-and-modularize

http://www.freelists.org/post/luajit/ENV-related-optimizations-Was-Make-the-VM-Luaversionagnostic-and-modularize,5

Only a few things need changing.

https://github.com/LuaJIT/LuaJIT/issues/79

Adding a multiparser setup like this would probably be more likely to get merged in to LuaJIT.

**Comment by katlogic** [comment]
> It can't do both Lua 5.1 and Lua 5.2 in the same VM state with limited (but good enough) interoperability.

Again, provide example. I'm using LJX with heavily mixed 5.1/5.2 code, though the support goes only as far as I needed it. 

As for _ENV, you need to keep ->env (for set/getenv()) in sync with _ENV - whenever _ENV is assigned, you need to patch up ->env of respective upscopes - https://github.com/katlogic/ljx/blob/master/src/vm_x86.dasc#L3944 otherwise getfenv() falls on its face later. LuaJIT does not care about _ENV at as far I know and other patches are incomplete (as they ignore 5.1 part of things just as you're pointing out). You also need to keep function ->env in linked list.

As for #len, how those differ between 5.1 and 5.2 again?

All that said, good luck bringing all this into lj repo, as ljx is slowly bitrotting away at the moment.

As for ABI, see https://github.com/katlogic/ljx/blob/master/src/Makefile#L103 - some of the 5.2 behavior is irreconcilable on ABI level (I'm using 5.1 compat by default).

**Comment by SoniEx2** [comment]
> As for _ENV, you need to keep ->env (for set/getenv()) in sync with _ENV - whenever _ENV is assigned, you need to patch up ->env of respective upscopes - https://github.com/katlogic/ljx/blob/master/src/vm_x86.dasc#L3944 otherwise getfenv() falls on its face later. LuaJIT does not care about _ENV at as far I know and other patches are incomplete (as they ignore 5.1 part of things just as you're pointing out). You also need to keep function ->env in linked list.

WTF NO JUST NO GTFO NOW

> It can't do both Lua 5.1 and Lua 5.2 in the same VM state with **limited (but good enough) interoperability**.
