### ISSUE TITLE
Scope issues?

### ISSUE THREAD

**Issue by gamax92** [katlogic/ljx#3]
Sometimes experiencing weird oddities such as this:

```
in 5.1, 5.2, 5.3, luajit: local i=1 while i do print(i) break end -> 1
in ljx: local i=1 while i do print(i) break end -> nil
```

But it works fine in any other kind of block like for loops, repeat until, do-end, etc.

Why do while loops specifically seem to break?

**Comment by katlogic** [comment]
Reverted in 641babb4ddc2341b3180aaf158c3faf87925d13d

For some background - https://www.freelists.org/post/luajit/Misbehaving-weak-tables-jit-load-barrier-buggy-gc

My fix back then was too poorly thought out, it needs to be handled elsewhere (ie gc step before TNEW, just as Rio Lua).

Turns out I had the DISABLE_UBKLUDGES enabled in my Makefile since ever, so never seen the bug.

Also, the parser is still quiete buggy in certain edge cases, as its one of the parts of LuaJIT which were half rewritten.

**Comment by gamax92** [comment]
Thank you, fix works perfectly.
